### ISSUE TITLE
Add formatting rule to be used from BUILD.bazel files

### ISSUE THREAD

**Issue by maikeru** [aspect-build/bazel-super-formatter#19]
I'm quite new to Bazel so please point out anything that doesn't make sense or isn't actually possible 😄 

**What?**
Would it be possible to add a formatting rule that can then be used from `BUILD.bazel` files? 

e.g. 
```starlark
# greeting/BUILD.bazel
format(
    name = "format_greeting_lib",
    srcs = glob("*.ts"),
)

# BUILD.bazel
format(
    name = "format_hello_lib",
    srcs = glob("*.ts"),
    deps = ["//greeting:format_greeting_lib"],
)
```
And then it could be run like this:
```
bazel run //src/format_hello_lib
```

As the `//greeting:format_greeting_lib` target is a dependency, it would also be formatted but could potentially be cached

**Why?**
As I understand it, currently bazel-super-formatter either formats all files in a workspace (with some exceptions based on .gitignore or other global-to-the-workspace config) or it needs to be told on the command line which files to format. 

Formatting all files in a workspace could get quite heavy and seems a shame not to take advantage of Bazel's build cache in this situation.

**Comment by alexeagle** [comment]
Good question, there are a couple reasons not to do it that way:
1. you shouldn't need to tell the formatter about files that don't participate in the dependency graph - imagine having to manually maintain a `filegroup` of all your markdown files just to get them into the formatter
1. running only on a subset of the files is right, however that's not a dependency graph shaped problem. Since formatters are syntactic and per-file, something like pre-commit.com is the right driver for this tool, so it runs only on your git staged changes and not over the whole repo.

Since `@aspect_rules_format//format` is an `sh_binary` target, you could in theory write your own stuff within your repo to use that as the `tool` in a run_binary or test target, if that's how you want to hold it - but I don't think this is right for most users so I'd rather not add anything first-class here for that use case.

**Comment by alexeagle** [comment]
The design doc might be useful as well: https://hackmd.io/0UgIb6gyTvSVX9N2vTPGug
