### ISSUE TITLE
[Bug]: prettier sh format broken with rules_js > 1.24.0

### ISSUE THREAD

**Issue by jsharpe** [aspect-build/bazel-super-formatter#41]
### What happened?

Format fails with the error:
```
[2023-04-19T23:58:05Z] Running Prettier...
[2023-04-19T23:58:05Z] [error] Cannot find module 'mvdan-sh'
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.1.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 2.0.0 using WORKSPACE

Language(s) and/or frameworks involved:
prettier / sh

**Comment by agluszak** [comment]
Appears to be fixed by #49

**Comment by tomasz-wozniak75** [comment]
We experience this problem when we use in bazel 7 with this option `--experimental_inprocess_symlink_creation=true` when it is set to false problem disappears. We have the same issue with other JS modules so we think that issue is in process symlink creation algorithm. Could you confirm this finding ? If you replicate the issue it should be reported to bazel project

**Comment by alexeagle** [comment]
@tomasz-wozniak75 I'm going to archive this repo shortly as it has been replaced by https://github.com/aspect-build/rules_lint which uses shfmt directly without prettier being involved.
So I'm closing this issue, could you please file another one if there's a similar problem in rules_lint?
